
[build-dependencies]

  [build-dependencies.tauri-build]
    features = []
    version = "1.3"

[dependencies]
  hcl-rs = "0.16.4"
  serde_json = "1.0"

  [dependencies.reqwest]
    features = ["json", "blocking"]
    version = "0.11"

  [dependencies.serde]
    features = ["derive"]
    version = "1.0"

  [dependencies.tauri]
    features = [ "fs-all", "updater", "system-tray", "process-exit", "dialog-all", "path-all", "shell-all"]
    version = "1.3"

[features]
  custom-protocol = ["tauri/custom-protocol"]

[package]
  authors = ["you"]
  description = "A Tauri App"
  edition = "2021"
  license = ""
  name = "prem-app"
  repository = ""
  version = "0.0.29"
